### PR TITLE
[i18n] French and Occitan

### PR DESCRIPTION
**Pull request by Quenty31**

### CODE REVIEW

**Comment by ChocoNutDancer** [comment]
this is the latest English.txt containing all the strings that are translated.  
[English.txt](https://github.com/screemerpl/cbleemsync/files/3287658/English.txt)

**Comment by Quenty31** [comment]
Thanks a lot @ChocoNutDancer !
I've just updated my file, I hope it's all good :)

**Comment by Quenty31** [comment]
I've just updated the file!
I don't use discord, I registered but it's way weird I don't see your channel.

**Comment by Quenty31** [comment]
> try this. it should be the main AutoBleem.
> https://discordapp.com/channels/538848850840911882/542109595443789834
> otherwise you can just put your two files here. I'm going to be checking in some other lang updates tonight.

Let's do this :) Thanks for checking! I hope it's fine

**Pull request closed without merging**
